<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\test.props" />
  <PropertyGroup>
    <Description>Queries.Core.Tests Class Library</Description>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\..\src\Queries.Core\Queries.Core.csproj" />
  </ItemGroup>
</Project>
