<Project Sdk="Microsoft.NET.Sdk">


  <Import Project="..\..\library.props" />
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.16" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Queries.EntityFrameworkCore.Extensions\Queries.EntityFrameworkCore.Extensions.csproj" />
    <ProjectReference Include="..\Queries.Renderers.SqlServer\Queries.Renderers.SqlServer.csproj" />
  </ItemGroup>
</Project>
