<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../test.props" />
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Xunit.Extensions.AssemblyFixture" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Queries.Renderers.SqlServer\Queries.Renderers.SqlServer.csproj" />
  </ItemGroup>
</Project>