<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../../test.props" />
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Npgsql" Version="8.0.6" />
        <PackageReference Include="Testcontainers.PostgreSql" Version="4.1.0" />
        <PackageReference Include="Xunit.Extensions.AssemblyFixture" Version="2.6.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Queries.Renderers.Postgres\Queries.Renderers.Postgres.csproj" />
    </ItemGroup>

</Project>
